- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move alertmanager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin
    remote_src: yes
    mode: "0777"

- name: "move amtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin
    remote_src: yes
    mode: "0777"

- name: "add alertmanager's configuration."
  become: true
  template:
    src: "files/alertmanager.yml"
    dest: "/etc/prometheus/alertmanager.yml"

- name: "configure Alertmanager as a service."
  become: true
  copy:
    src: files/alertmanager.service
    dest: /etc/systemd/system/

- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes

- name: "copy new rule for alerts."
  become: true
  copy:
    src: files/rules.yml
    dest: /etc/prometheus/rules.yml

- name: reload systemd
  become: yes
  shell: |
    systemctl restart prometheus
