route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "email-me"
receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://127.0.0.1:5001/"
  - name: email-me
    email_configs:
      - to: abubakarhassan59+prometheus@gmail.com
        from: abubakarhassan59@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: abubakarhassan59@gmail.com
        auth_identity: abubakarhassan59@gmail.com
        auth_password: davfnwyegkiehnxn
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
